### PR TITLE
Export `wamr_sys`.

### PR DESCRIPTION
**Pull request by AlixANNERAUD**
I think this won't harm anyone.

### CODE REVIEW

**Comment by lum1n0us** [comment]
we don't want people use wamr-sys directly. It will be a nightmare to use "C" logic to programming in Rust.

**Comment by AlixANNERAUD** [comment]
Perhaps, but in the meantime, this crate is very incomplete. It's essential to allow the end user some degree of freedom if needed (which I am desperately hoping to have). Alternatively, `wamr-sys` and `warm-rust-sdk` should be separated. Allowing the end user to decide whether to use `wamr-sys` or not doesn't harm anyone. Many Rust crates have adopted the same approach.

**Comment by lum1n0us** [comment]
Please let me know your requirement. We shall develop new APIs.

**Comment by AlixANNERAUD** [comment]
I proposed the addition of the [execution environment](https://github.com/bytecodealliance/wamr-rust-sdk/pull/35), which is necessary for address translation, heap allocation in the Wasm app, setting user data, and address validation. However, this was refused since it wasn't safe. In addition, WAMR C API allows for the creation of thread environments for host created thread.

I understand the will to offer a completely safe API for WAMR, but currently, `wamr_rust_sdk` cannot fully leverage the capabilities of WAMR, which could be frustrating for end users. This is not a criticism but a fact: the two only maintainers of this repository seem to be already quite occupied with WAMR directly (and I prefer that WAMR is refined before wamr_rust_sdk). I completely understand that `wamr_rust_sdk` is not yet up to par, but please allow us to at least take advantage of the missing features in `wamr_rust_sdk` through the C API for now.

**Comment by lum1n0us** [comment]
Fair enough. let's do this.

**Comment by AlixANNERAUD** [comment]
Thx ☺️

**Pull request merged**
